# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('feedback', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
