# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtmRefill',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('atm_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'atm_refill',
                'managed': False,
            },
        ),
    ]
