# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('ua_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=25)),
                ('ifsc_code', models.CharField(max_length=25)),
                ('type_of_account', models.CharField(max_length=25)),
                ('balance', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
    ]
