# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reply', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reply',
                'managed': False,
            },
        ),
    ]
