# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('atm_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.IntegerField()),
                ('location', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('latitude', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'atm',
                'managed': False,
            },
        ),
    ]
