# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('usename', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
