# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminComplaint',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'admin_complaint',
                'managed': False,
            },
        ),
    ]
