# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtmTransactions',
            fields=[
                ('atmtr_id', models.AutoField(primary_key=True, serialize=False)),
                ('atm_id', models.IntegerField()),
                ('u_id', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=25)),
                ('account_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'atm_transactions',
                'managed': False,
            },
        ),
    ]
