# Generated by Django 3.1.6 on 2021-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.IntegerField()),
                ('atm_id', models.IntegerField()),
                ('qr', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'qr',
                'managed': False,
            },
        ),
    ]
